inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  Exclude:
    - tmp/**/*
    - db/**/*
    - bin/**/*
    - scripts/**/*
    - node_modules/**/*
  TargetRubyVersion: 2.5.0

Layout/AlignParameters:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
